# Generated by Django 3.1.5 on 2021-01-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution', models.CharField(max_length=100)),
                ('poke_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
